### PR TITLE
Use _DEFAULT_SOURCE, not deprecated _BSD_SOURCE

### PR DESCRIPTION
**Pull request by toofishes**
This fixes the compile error introduced in commit f152bf6. Reported in #142.

/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]

### CODE REVIEW

**Comment by mutability** [comment]
Looks like this means we can remove _POSIX_SOURCE too
